name: PlugRole
version: '1.0-SNAPSHOT'
main: me.Saciek.plugRole.PlugRole
api-version: '1.20'
authors: [ Saciek ]
description: Plugin that gives Roles to players
commands:
  MinersPotion:
    description: This commands check if Player has 12 emeralds to get a potion that give basic effects for miners such as haste.
    usage: /<command>
    aliases: [PotionForMining, x2Potion, UberPotion]
  EndurancePotion:
    description: This commands check if Player has 32 gold to get a potion that give basic endurance effects such as speed etc.
    usage: /<command>
    aliases: [EndurancePotion, PotionOfEndurance]
  help_potion:
    description: Gives a simple description on how to use all plugin commands
    usage: /<command>
    aliases: [help_potionPlug, potion_help]
